tap "nikitabobko/tap"
tap "railwaycat/emacsmacport"

brew "ast-grep"
brew "bat"
brew "btop"
brew "cmake"
brew "colima"
brew "coreutils"
brew "docker"
brew "fd"
brew "findutils" # Doom recommends GNU find on macOS
brew "fzf"
brew "gh"
brew "git"
brew "go"
brew "gnu-tar" # Doom recommends GNU tar on macOS
brew "ispell"
brew "lazygit"
brew "neovim"
brew "node"
brew "python"
brew "ripgrep"
brew "rust"
brew "shellcheck"
brew "starship"
brew "tailscale"
brew "tldr"
brew "tmux"
brew "tree"
brew "tree-sitter-cli"
brew "typst"
brew "uv"
brew "xcodegen"
brew "zoxide"
# Doom's preferred macOS port; explicitly select Emacs 29 (29.1+ required).
# Dynamic modules are enabled by default; do not pass the obsolete --with-modules.
# GUI registration and Doom core installation remain explicit: docs/doom-emacs.md.
brew "railwaycat/emacsmacport/emacs-mac@29", args: ["with-native-compilation"]

cask "nikitabobko/tap/aerospace"
cask "alt-tab"
cask "1password"
cask "discord"
cask "figma"
cask "font-iosevka-nerd-font"
cask "font-iosevka-term-nerd-font"
cask "font-jetbrains-mono-nerd-font"
cask "font-noto-sans-symbols"
cask "font-noto-sans-symbols-2"
cask "ghostty"
cask "protonvpn"
cask "qbittorrent"
cask "raycast"
