tap "nikitabobko/tap"
tap "railwaycat/emacsmacport"

brew "ast-grep"
brew "bat"
brew "btop"
brew "cmake"
brew "colima"
brew "coreutils"
brew "docker"
brew "fd"
brew "findutils" # Doom recommends GNU find on macOS
brew "fzf"
brew "gh"
brew "git"
brew "go"
brew "gnu-tar" # Doom recommends GNU tar on macOS
brew "hunk"
brew "ispell"
brew "lazygit"
brew "libtool"
brew "neovim"
brew "node"
brew "python"
brew "ripgrep"
brew "rust"
brew "shellcheck"
brew "starship"
brew "tailscale"
brew "tldr"
brew "tmux"
brew "tree"
brew "tree-sitter-cli"
# Provides latex and dvisvgm for Org-mode formula previews.
brew "texlive"
brew "typst"
brew "uv"
brew "xcodegen"
brew "zoxide"
# Railwaycat's experimental Emacs 31 snapshot (not HEAD); see docs/doom-emacs.md.
# Tree-sitter and dynamic modules are enabled by default; no --with-modules.
# GUI registration and Doom core installation remain explicit.
brew "railwaycat/emacsmacport/emacs-mac@31exp", args: ["with-native-compilation", "with-librsvg", "with-xwidgets", "with-starter"]

cask "nikitabobko/tap/aerospace"
cask "alt-tab"
cask "1password"
cask "discord"
cask "figma"
cask "font-iosevka-nerd-font"
cask "font-iosevka-term-nerd-font"
cask "font-jetbrains-mono-nerd-font"
cask "font-noto-sans-symbols"
cask "font-noto-sans-symbols-2"
cask "ghostty"
cask "protonvpn"
cask "qbittorrent"
cask "raycast"
