tap "nikitabobko/tap"

cask "nikitabobko/tap/aerospace"
cask "alt-tab"
cask "discord"
cask "figma"
cask "font-iosevka-nerd-font"
cask "font-iosevka-term-nerd-font"
cask "font-jetbrains-mono-nerd-font"
cask "font-noto-sans-symbols"
cask "font-noto-sans-symbols-2"
cask "ghostty"
cask "protonvpn"
cask "qbittorrent"
cask "raycast"
