palette = 0=#252530
palette = 1=#d8647e
palette = 2=#7fa563
palette = 3=#f3be7c
palette = 4=#7e98e8
palette = 5=#bb9dbd
palette = 6=#5f8787
palette = 7=#c1c1c1
palette = 8=#606079
palette = 9=#d8647e
palette = 10=#7fa563
palette = 11=#f3be7c
palette = 12=#7e98e8
palette = 13=#bb9dbd
palette = 14=#9bb4bc
palette = 15=#cdcdcd
background = #000000
foreground = #c1c1c1
cursor-color = #c1c1c1
selection-background = #fbcb97
selection-foreground = #000000
background-opacity = 0.9
background-blur = true
