#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

yabai -m config external_bar all:40:0 \
  mouse_follows_focus on \
  focus_follows_mouse on \
  window_opacity off
