#!/bin/bash
code --install-extension aaron-bond.better-comments
code --install-extension alefragnani.bookmarks
code --install-extension asvetliakov.vscode-neovim
code --install-extension christian-kohler.path-intellisense
code --install-extension dart-code.dart-code
code --install-extension dart-code.flutter
code --install-extension drcika.apc-extension
code --install-extension entuent.fira-code-nerd-font
code --install-extension esbenp.prettier-vscode
code --install-extension github.copilot
code --install-extension github.copilot-chat
code --install-extension golang.go
code --install-extension jdinhlife.gruvbox
code --install-extension jonathanharty.gruvbox-material-icon-theme
code --install-extension nash.awesome-flutter-snippets
code --install-extension sainnhe.gruvbox-material
code --install-extension tomrijndorp.find-it-faster
code --install-extension usernamehw.errorlens
code --install-extension vspacecode.whichkey
