#!/usr/bin/env bash

url=$(git remote get-url origin)
if [[ $url == *github.com* ]]; then
    if [[ $url == git@* ]]; then
        url="${url#git@}"
        url="${url/:/\/}" 
        url="https://$url"
    fi
    
    if [[ "$OSTYPE" == "darwin"* ]]; then
        open "$url"
    else
        xdg-open "$url"
    fi
fi
